/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "dashboard": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "guru.index": [],
    "guru.create": [],
    "guru.store": [],
    "guru.show": [
        {
            "name": "guru",
            "required": true
        }
    ],
    "guru.edit": [
        {
            "name": "guru",
            "required": true
        }
    ],
    "guru.update": [
        {
            "name": "guru",
            "required": true
        }
    ],
    "guru.destroy": [
        {
            "name": "guru",
            "required": true
        }
    ],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": []
}
}
export {};
